# Science is based on peer-review - a process where scientist evaluate other scientist. Typically, a candidate submits their work, which is then distributed to 2-3 reviewers by a single central person (i.e. a coordinator). This is done for a variety of things - for example, a poster submission to a conference, an application for an award, or a manuscript for publication. A key aspect is to best match the candidate's work to the expertise (both methodology and topical) of the reviewers without over burdening (i.e. too much work) the reviewers themselves.

You are the coordinator and must match a list of candidate to a list of reviewers for the year 2020.

Task

Write a program (i.e. 'review_matching.py') that does the following
That reads in the following two csv files:
reviewers_data.csv - name, gender, email, methodologies, topics, and 4 years (2016-2019) that indicate if they performed a review
candidates_data.csv - name, gender, email, methodologies used, and topics of work
For each candidate, performs an optimal matching between the candidate and 3 reviewers based on
matching the methodologies,
matching the topics, and
by giving higher priority to reviewers who have not recently performed a review
Create the matching such that only 10 reviewers (i.e the best possible options) are selected from the 50 possible
Save the resulting matches to a new csv file in a clear and easy-to-understand manner
For clarity:

Each cadidate should be reviewed by 3 different (i.e. unique) reviewers
Only 10 reviewers should be used in total, with each one doing 3 unique reviews

Include at the top of the code as a block comment (i.e. triple quotations) a clear statement of your individual contributions

For Example:

"""

Student 1:

a. Conceptual development b. Primary developer of function_1_name c. Codeveloper of error functions etc.
Student 2:

a. Conceptual development b. Primary developer of function_2_name c. Codeveloper of error functions d. Primary developer of user interface etc.<br>
"""

In [77]:
import csv
import numpy as np
import pandas as pd

# read in the 
reviewer = pd.read_csv("reviewers_data.csv",sep = ";")
candidates = pd.read_csv("candidates_data.csv",sep = ";")

#Datenframe erzeugen
data = {'Candidate' : [],
        'Reviewer1' : [],
        'Reviewer2' : [],
        'Reviewer3' : [],
       }
df_final = pd.DataFrame(data)
df_final['Candidate'] = candidates['Name']

def getlistwithMatchpoints(candidat = None, dataframereview = None):
    
    df_temp = pd.DataFrame({'Reviewer' : [],'Matchpoints' : [] , 'Years_Without_Rev' : []})
    df_temp['Reviewer'] = reviewer['Name']

    for index_r,row_r in dataframereview.iterrows():
        #Matchpoints 
        topic = np.isin(candidat[4].split(','),row_r[4].split(','))
        methodologies = np.isin(candidat[3].split(','),row_r[3].split(','))
    
        df_temp.loc[index_r, 'Matchpoints'] =  np.sum(topic) + np.sum(methodologies)
    
    
        # years last review
        year = 8
        year_counter = 0
        for i in range(3):
        
            if 'No' in row_r[year]:
                year_counter += 1
            else :
                break;
            year -= 1
            df_temp.loc[index_r, 'Years_Without_Rev'] =  year_counter
 
    df_tempo = df_temp.sort_values(by = ['Matchpoints', 'Years_Without_Rev'], ascending = False)
    return (df_tempo.reset_index())


def filldatabase( df_t_final = None , df_candidate = None , df_rev = None ):

    for index_d,row_d in df_can.iterrows():
        temp = getlistwithMatchpoints(row_d, df_rev)
        for i in range(3):
            df_t_final.loc[index_d, 'Reviewer{}'.format(i+1)] = temp.loc[i,'Reviewer']
                
    return df_t_final
        
tabelle = datenbankfüllen(df_final, candidates , reviewer)

tabelle

           Candidate         Reviewer1           Reviewer2          Reviewer3
0     Hillary Hofman        Jim Uhlman       Andreas Bento  Cristobal Maillet
1       Marica Bross      Geri Haislip         Silas Knapp    Giuseppe Updike
2   Bobby Plascencia    Elba Choudhury         Alease Zinn        Silas Knapp
3       Virgil Lebel   Giuseppe Updike      Elba Choudhury      Lesha Christy
4     Danuta Voegele   Giuseppe Updike         Jan Pfeffer      Pearlene Mara
5        Shana Galey   Jutta Singleton       Terrie Riffel        Elbert Lind
6     Rosita Cornejo        Roy Zeller  Charline Clairmont       Marco Kerwin
7  Tiffiny Bradfield  Delsie Mccaffery     Giuseppe Updike          Tim Dungy
8          Devon Cyr    Shawanda Finks        Cammy Nalsam        Alease Zinn
9   Frank Hellickson       Alease Zinn      Elba Choudhury       Cammy Nalsam